name: Build Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps: 
      - name: install python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: test
        run: |
          pytest
